---
title: "Random Brussels Sprouts with Ajax"
type: "challenge"
description: "Using Ajax to generate random brussels sprouts recipes"
visibility: "assign"
tags: "ajax, javascript"
ignore:
- "evening-ajax-brussels-sprouts.md"
